# Generated by Django 5.1.4 on 2026-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
